file_settings:
  path: /file/settings
  defaults: { _controller: GravityFileBundle:File:settings }

file_list:
  path:  /file
  defaults: { _controller: GravityFileBundle:File:list }

file_new:
  path:  /file/new
  defaults: { _controller: GravityFileBundle:File:new }

#file_view:
#    path:  /{id}
#    defaults: { _controller: GravityFileBundle:File:view }
#    requirements:
#       id: \d+

file_edit:
  path:  /file/{id}/edit
  defaults: { _controller: GravityFileBundle:File:edit }
  requirements:
     id: \d+

#file_upload_edit:
#    path: /{id}/upload
#    defaults: { _controller: GravityFileBundle:File:uploadEdit }
#    requirements:
#       id: \d+

file_upload:
  path: /file/upload
  defaults: { _controller: GravityFileBundle:File:upload }

image_style_list:
  path: /file/image-styles
  defaults: { _controller: GravityFileBundle:ImageStyle:list }

image_style_new:
  path: /file/image-styles/new
  defaults: { _controller: GravityFileBundle:ImageStyle:new }

image_style_edit:
  path: /file/image-styles/{imageStyle}/edit
  defaults: { _controller: GravityFileBundle:ImageStyle:edit }


image_style_operation_new:
  path: /file/image-styles/{imageStyle}/operation/new
  defaults: { _controller: GravityFileBundle:ImageStyle:newOperation }

image_style_operation_edit:
  path: /file/image-styles/{imageStyle}/operation/{imageStyleOperation}/edit
  defaults: { _controller: GravityFileBundle:ImageStyle:editOperation }

image_style_operation_settings:
  path: /file/image-styles/{imageStyle}/operation/{imageStyleOperation}/settings
  defaults: { _controller: GravityFileBundle:ImageStyle:editOperationSettings }
