services:
  gravity.image_style_manager:
    class: Gravity\FileBundle\ImageStyler\ImageStyleManager
    arguments:
      - @gravity.image_style.operation_manager

  gravity.image_style.operation_manager:
    class: Gravity\FileBundle\ImageStyler\Operation\OperationManager

  gravity.image_style_factory:
    class: Gravity\FileBundle\ImageStyler\ImageStyleFactory
    arguments:
      - @gravity.image_style.operation_manager

  # Image Style Operations
  gravity.image_style.operation.gd_optimiser:
    class: Gravity\FileBundle\ImageStyler\Operation\GDOptimiser\GDOptimiser
    tags:
      - { name: image_style.operation }

  gravity.image_style.operation.node_optimiser:
    class: Gravity\FileBundle\ImageStyler\Operation\NodeOptimiser\NodeOptimiser
    tags:
      - { name: image_style.operation }
