imports:
  - { resource: services/field_file.yml }
  - { resource: services/field_image.yml }

parameters:
  gravity.file_manager.class: Gravity\FileBundle\File\FileManager

services:

  #
  # File Manager
  gravity.file_manager:
    class: %gravity.file_manager.class%
    arguments:
      - @gravity_cms.config_manager
      - @doctrine.orm.default_entity_manager
      - @knp_gaufrette.filesystem_map

  #
  # Forms
  gravity.file.form.file_configuration:
    class: Gravity\FileBundle\Configuration\FileConfigurationForm
    arguments:
      - @knp_gaufrette.filesystem_map
    tags:
      - { name: form.type, alias: file_configuration }

  gravity.file.form.gravity_file:
    class: Gravity\FileBundle\Form\GravityFileForm
    tags:
      - { name: form.type, alias: gravity_file }

  gravity.file.form.file_browser:
    class: Gravity\FileBundle\Form\Type\FileBrowserType
    tags:
      - { name: form.type, alias: file_browser }

  gravity.file.form.image_browser:
    class: Gravity\FileBundle\Form\Type\ImageBrowserType
    tags:
      - { name: form.type, alias: image_browser }

  gravity.file.form.file_collection:
    class: Gravity\FileBundle\Form\Type\FileCollectionType
    tags:
      - { name: form.type, alias: file_collection }


  #
  # Liip imagine stream cache respolver:
  liip.cache.resolver.stream_cache:
    class: Gravity\FileBundle\Liip\Imagine\Cache\Resolver\StreamCacheResolver
    arguments:
      - @filesystem
      - @router.request_context
      - @knp_gaufrette.filesystem_map
      - %gravity_default_filesystem%
      - styles/
    tags:
      - { name: liip_imagine.cache.resolver, resolver: stream }
